package io.github.afgprojects.framework.core.invocation;

import java.util.List;

/**
 * Simple record-based implementation of {@link OperationMetadata}.
 * <p>
 * Generated by APT processor at compile time and instantiated in ServiceMetadata classes.
 */
public record SimpleOperationMetadata(
    String name, String description, MethodKey method,
    List<ParameterMetadata> parameters, String returnType, String returnDescription,
    String permission, List<String> requiredRoles,
    boolean audit, boolean tenantScope, boolean dataScope,
    boolean async, boolean deprecated, String inputSchema, boolean paged
) implements OperationMetadata {}
