package io.github.afgprojects.framework.core.invocation;

import java.util.List;

/**
 * Simple record-based implementation of {@link ParameterMetadata}.
 * <p>
 * Generated by APT processor at compile time and instantiated in ServiceMetadata classes.
 */
public record SimpleParameterMetadata(
    String name, String type, boolean required, String defaultValue,
    int index, String description, List<String> enumValues, boolean injected
) implements ParameterMetadata {}
