package io.github.afgprojects.framework.data.core.dialect;

import io.github.afgprojects.framework.data.core.page.PageRequest;
import org.jspecify.annotations.NonNull;

/**
 * Oracle 数据库方言
 */
public class OracleDialect implements Dialect {

    @Override
    public @NonNull DatabaseType getDatabaseType() {
        return DatabaseType.ORACLE;
    }

    @Override
    public @NonNull String getPaginationSql(@NonNull String sql, long offset, long limit) {
        // Oracle 12c+ 使用 FETCH FIRST 语法
        return "SELECT * FROM (" + sql + ") OFFSET " + offset + " ROWS FETCH NEXT " + limit + " ROWS ONLY";
    }

    @Override
    public @NonNull String getPaginationSql(@NonNull String sql, @NonNull PageRequest pageable) {
        return getPaginationSql(sql, pageable.offset(), pageable.size());
    }

    @Override
    public boolean supportsLimitOffset() {
        return false;  // Oracle 12c+ 支持 OFFSET FETCH，但传统方式不支持
    }

    @Override
    public boolean supportsFetchFirst() {
        return true;  // Oracle 12c+
    }

    @Override
    public @NonNull String getIdentifierQuote() {
        return "\"";
    }

    @Override
    public @NonNull String quoteIdentifier(@NonNull String identifier) {
        return getIdentifierQuote() + identifier + getIdentifierQuote();
    }

    @Override
    public @NonNull String getCurrentTimeFunction() {
        return "SYSDATE";
    }

    @Override
    public @NonNull String getCurrentDateFunction() {
        return "SYSDATE";
    }

    @Override
    public @NonNull String getCurrentTimestampFunction() {
        return "SYSTIMESTAMP";
    }

    @Override
    public boolean supportsAutoIncrement() {
        return true;  // Oracle 12c+ supports GENERATED AS IDENTITY
    }

    @Override
    public boolean supportsSequence() {
        return true;
    }

    @Override
    public @NonNull String getAutoIncrementSyntax() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public @NonNull String getSequenceNextValueSql(@NonNull String sequenceName) {
        return "SELECT " + sequenceName + ".NEXTVAL FROM DUAL";
    }

    @Override
    public @NonNull String getSqlType(@NonNull Class<?> javaType) {
        if (javaType == String.class) return "VARCHAR2(255)";
        if (javaType == Integer.class || javaType == int.class) return "NUMBER(10)";
        if (javaType == Long.class || javaType == long.class) return "NUMBER(19)";
        if (javaType == Double.class || javaType == double.class) return "NUMBER(19,4)";
        if (javaType == Float.class || javaType == float.class) return "NUMBER(19,4)";
        if (javaType == Boolean.class || javaType == boolean.class) return "NUMBER(1)";
        if (javaType == java.time.LocalDateTime.class) return "TIMESTAMP";
        if (javaType == java.time.LocalDate.class) return "DATE";
        if (javaType == java.time.LocalTime.class) return "TIMESTAMP";
        if (javaType == java.math.BigDecimal.class) return "NUMBER(19,4)";
        if (javaType == byte[].class) return "BLOB";
        return "VARCHAR2(255)";
    }

    @Override
    public @NonNull String getLikeWildcard() {
        return "%";
    }

    @Override
    public boolean supportsForUpdate() {
        return true;
    }

    @Override
    public @NonNull String getForUpdateSyntax() {
        return "FOR UPDATE";
    }
}