package io.github.afgprojects.framework.data.core.dialect;

import org.jspecify.annotations.NonNull;

/**
 * Oracle 方言实现。
 */
public class OracleDialect extends AbstractDialect {

    @Override
    public @NonNull DatabaseType getDatabaseType() {
        return DatabaseType.ORACLE;
    }

    @Override
    public @NonNull String getIdentifierQuote() {
        return "\"";
    }

    @Override
    public @NonNull String getCurrentTimeFunction() {
        return "SYSDATE";
    }

    @Override
    public @NonNull String getCurrentDateFunction() {
        return "SYSDATE";
    }

    @Override
    public @NonNull String getCurrentTimestampFunction() {
        return "SYSTIMESTAMP";
    }

    @Override
    public boolean supportsLimitOffset() {
        return false;
    }

    @Override
    public boolean supportsFetchFirst() {
        return true;
    }

    @Override
    public @NonNull String getPaginationSql(@NonNull String sql, long offset, long limit) {
        return "SELECT * FROM (" + sql + ") OFFSET " + offset + " ROWS FETCH NEXT " + limit + " ROWS ONLY";
    }

    @Override
    public @NonNull String getAutoIncrementSyntax() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public @NonNull String getSequenceNextValueSql(@NonNull String sequenceName) {
        return "SELECT " + sequenceName + ".NEXTVAL FROM DUAL";
    }

    @Override
    protected void configureSqlTypeMap(java.util.Map<Class<?>, String> map) {
        map.put(String.class, "VARCHAR2(255)");
        map.put(Boolean.class, "NUMBER(1)");
        map.put(boolean.class, "NUMBER(1)");
        map.put(Integer.class, "NUMBER(10)");
        map.put(int.class, "NUMBER(10)");
        map.put(Long.class, "NUMBER(19)");
        map.put(long.class, "NUMBER(19)");
        map.put(Double.class, "NUMBER(19,4)");
        map.put(double.class, "NUMBER(19,4)");
        map.put(Float.class, "NUMBER(19,4)");
        map.put(float.class, "NUMBER(19,4)");
        map.put(java.math.BigDecimal.class, "NUMBER(19,4)");
        map.put(byte[].class, "BLOB");
        map.put(java.sql.Timestamp.class, "TIMESTAMP");
        map.put(java.time.LocalDateTime.class, "TIMESTAMP");
        map.put(java.time.LocalTime.class, "TIMESTAMP");
        map.put(java.time.OffsetDateTime.class, "TIMESTAMP WITH TIME ZONE");
        map.put(java.time.ZonedDateTime.class, "TIMESTAMP WITH TIME ZONE");
        map.put(Object.class, "VARCHAR2(255)");
    }
}
