package io.github.afgprojects.framework.apt.entity;

import javax.annotation.processing.ProcessingEnvironment;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.Writer;
import java.util.List;

/**
 * CommonFieldMetadata 类生成器
 * <p>
 * 生成包含所有注册字段的 CommonFieldMetadata 类。
 */
class CommonFieldMetadataGenerator {

    private final ProcessingEnvironment processingEnv;

    CommonFieldMetadataGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    /**
     * 生成 CommonFieldMetadata 类
     *
     * @param packageName 目标包名
     * @param fields      所有注册的字段
     */
    void generate(String packageName, List<CommonFieldInfo> fields) {
        String className = "CommonFieldMetadata";
        String fullName = packageName + ".metadata." + className;

        try {
            String sourceCode = generateSourceCode(packageName, className, fields);
            writeSourceFile(fullName, sourceCode);
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                "Failed to generate CommonFieldMetadata: " + e.getMessage());
        }
    }

    /**
     * 生成源码
     */
    private String generateSourceCode(String packageName, String className, List<CommonFieldInfo> fields) {
        StringBuilder sb = new StringBuilder();

        // 包声明
        sb.append("package ").append(packageName).append(".metadata;\n\n");

        // 导入
        sb.append("import io.github.afgprojects.framework.data.core.metadata.*;\n");
        sb.append("import java.time.LocalDateTime;\n\n");

        // 类注释
        sb.append("/**\n");
        sb.append(" * 通用字段元数据类（自动生成）\n");
        sb.append(" * <p>\n");
        sb.append(" * 包含框架内置字段和注册字段的元数据常量。\n");
        sb.append(" * @generated by AFG Framework APT\n");
        sb.append(" */\n");

        // 类声明
        sb.append("public final class ").append(className).append(" {\n\n");

        // 私有构造函数
        sb.append("    private ").append(className).append("() {}\n\n");

        // 常量声明 - 框架内置字段
        sb.append("    // ==================== 框架内置字段 ====================\n\n");
        for (CommonFieldInfo field : fields) {
            if (field.source() == FieldSource.FRAMEWORK) {
                sb.append("    /**\n");
                sb.append("     * ").append(field.propertyName()).append(" 字段元数据\n");
                sb.append("     */\n");
                String innerClassName = toCamelCase(field.name()) + "FieldMetadata";
                sb.append("    public static final DatabaseFieldMetadata ").append(field.name())
                  .append(" = new ").append(innerClassName).append("();\n\n");
            }
        }

        // 注册字段
        sb.append("    // ==================== 注册字段 ====================\n\n");
        for (CommonFieldInfo field : fields) {
            if (field.source() != FieldSource.FRAMEWORK) {
                sb.append("    /**\n");
                sb.append("     * ").append(field.propertyName()).append(" 字段元数据\n");
                sb.append("     */\n");
                String innerClassName = toCamelCase(field.name()) + "FieldMetadata";
                sb.append("    public static final DatabaseFieldMetadata ").append(field.name())
                  .append(" = new ").append(innerClassName).append("();\n\n");
            }
        }

        // 动态创建方法
        sb.append("    // ==================== 动态创建方法 ====================\n\n");
        sb.append("    /**\n");
        sb.append("     * 创建主键字段元数据\n");
        sb.append("     */\n");
        sb.append("    public static DatabaseFieldMetadata id(Class<?> idType) {\n");
        sb.append("        return new IdFieldMetadata(idType);\n");
        sb.append("    }\n\n");

        // 内部类
        sb.append("    // ==================== 内部类 ====================\n\n");
        for (CommonFieldInfo field : fields) {
            sb.append(generateInnerClass(field));
        }

        // IdFieldMetadata 内部类
        sb.append(generateIdFieldMetadataClass());

        sb.append("}\n");

        return sb.toString();
    }

    /**
     * 生成内部类代码
     */
    private String generateInnerClass(CommonFieldInfo field) {
        StringBuilder sb = new StringBuilder();
        String innerClassName = toCamelCase(field.name()) + "FieldMetadata";

        sb.append("    private static final class ").append(innerClassName)
          .append(" implements DatabaseFieldMetadata {\n");

        sb.append("        @Override\n");
        sb.append("        public String getPropertyName() {\n");
        sb.append("            return \"").append(field.propertyName()).append("\";\n");
        sb.append("        }\n\n");

        sb.append("        @Override\n");
        sb.append("        public String getColumnName() {\n");
        sb.append("            return \"").append(field.columnName()).append("\";\n");
        sb.append("        }\n\n");

        sb.append("        @Override\n");
        sb.append("        public Class<?> getFieldType() {\n");
        sb.append("            return ").append(field.fieldType()).append(".class;\n");
        sb.append("        }\n\n");

        sb.append("        @Override\n");
        sb.append("        public boolean isId() {\n");
        sb.append("            return ").append(field.isId()).append(";\n");
        sb.append("        }\n\n");

        sb.append("        @Override\n");
        sb.append("        public boolean isGenerated() {\n");
        sb.append("            return ").append(field.isGenerated()).append(";\n");
        sb.append("        }\n");

        sb.append("    }\n\n");

        return sb.toString();
    }

    /**
     * 生成 IdFieldMetadata 内部类
     */
    private String generateIdFieldMetadataClass() {
        return """
            private static final class IdFieldMetadata implements DatabaseFieldMetadata {
                private final Class<?> idType;

                IdFieldMetadata(Class<?> idType) {
                    this.idType = idType;
                }

                @Override
                public String getPropertyName() {
                    return "id";
                }

                @Override
                public String getColumnName() {
                    return "id";
                }

                @Override
                public Class<?> getFieldType() {
                    return idType;
                }

                @Override
                public boolean isId() {
                    return true;
                }

                @Override
                public boolean isGenerated() {
                    return true;
                }
            }

        """;
    }

    /**
     * 转换为驼峰命名
     */
    private String toCamelCase(String name) {
        StringBuilder sb = new StringBuilder();
        String[] parts = name.split("_");
        for (int i = 0; i < parts.length; i++) {
            if (i == 0) {
                sb.append(parts[i].toLowerCase());
            } else {
                sb.append(Character.toUpperCase(parts[i].charAt(0)));
                sb.append(parts[i].substring(1).toLowerCase());
            }
        }
        return sb.toString();
    }

    /**
     * 写入源文件
     */
    private void writeSourceFile(String className, String sourceCode) throws IOException {
        JavaFileObject file = processingEnv.getFiler().createSourceFile(className);
        try (Writer writer = file.openWriter()) {
            writer.write(sourceCode);
        }
    }
}
