package io.github.afgprojects.framework.apt.entity;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.type.TypeKind;
import javax.lang.model.util.ElementFilter;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.Writer;
import java.util.*;

/**
 * 实体元数据注解处理器
 * <p>
 * 扫描所有带有 @AfEntity 注解的类，生成元数据类。
 * 生成的元数据类实现 DatabaseEntityMetadata 接口，提供编译时确定的实体元数据。
 *
 * <pre>
 * 示例输入：
 * {@code
 * @AfEntity
 * @Table(name = "sys_user")
 * public class User {
 *     @Id
 *     private Long id;
 *
 *     @Column(name = "is_deleted")
 *     private Boolean deleted;
 *
 *     private String userName;
 * }
 * }
 *
 * 生成输出：
 * {@code
 * package io.github.example.metadata;
 *
 * public class UserMetadata implements DatabaseEntityMetadata<User> {
 *     // ... 自动生成的实现
 * }
 * }
 * </pre>
 */
@SupportedAnnotationTypes("io.github.afgprojects.framework.apt.entity.AfEntity")
@SupportedSourceVersion(SourceVersion.RELEASE_25)
public class EntityMetadataProcessor extends AbstractProcessor {

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
            "AFG Entity Metadata Processor initialized");
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            return false;
        }

        for (TypeElement annotation : annotations) {
            for (Element element : roundEnv.getElementsAnnotatedWith(annotation)) {
                if (element instanceof TypeElement typeElement) {
                    try {
                        processEntityElement(typeElement);
                    } catch (Exception e) {
                        processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                            "Failed to process entity: " + e.getMessage(), element);
                    }
                }
            }
        }

        return true;
    }

    /**
     * 处理实体元素，生成元数据类
     */
    private void processEntityElement(TypeElement typeElement) {
        String className = typeElement.getQualifiedName().toString();
        String packageName = extractPackageName(className);
        String simpleName = typeElement.getSimpleName().toString();
        String metadataClassName = simpleName + "Metadata";
        String metadataFullName = packageName + ".metadata." + metadataClassName;

        processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
            "Generating metadata for: " + className, typeElement);

        try {
            String sourceCode = generateMetadataClass(typeElement, packageName, metadataClassName);
            writeSourceFile(metadataFullName, sourceCode);
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                "Failed to generate metadata: " + e.getMessage(), typeElement);
        }
    }

    /**
     * 生成元数据类源码
     */
    private String generateMetadataClass(TypeElement typeElement, String packageName, String metadataClassName) {
        StringBuilder sb = new StringBuilder();

        // 包声明
        sb.append("package ").append(packageName).append(".metadata;\n\n");

        // 导入
        sb.append("import io.github.afgprojects.framework.data.core.metadata.*;\n");
        sb.append("import io.github.afgprojects.framework.data.core.relation.RelationMetadata;\n");
        sb.append("import java.util.*;\n");
        sb.append("import java.util.stream.Collectors;\n");
        sb.append("import ").append(typeElement.getQualifiedName()).append(";\n\n");

        // 类注释
        sb.append("/**\n");
        sb.append(" * 自动生成的实体元数据类\n");
        sb.append(" * @generated by AFG Framework APT\n");
        sb.append(" * @see ").append(typeElement.getQualifiedName()).append("\n");
        sb.append(" */\n");

        // 类声明
        sb.append("public class ").append(metadataClassName)
          .append(" implements DatabaseEntityMetadata<").append(typeElement.getSimpleName()).append("> {\n\n");

        // 表名
        String tableName = extractTableName(typeElement);
        sb.append("    private static final String TABLE_NAME = \"").append(tableName).append("\";\n\n");

        // 实体类引用
        sb.append("    private final Class<").append(typeElement.getSimpleName()).append("> entityClass = ")
          .append(typeElement.getSimpleName()).append(".class;\n\n");

        // 字段列表
        List<FieldInfo> fields = extractFields(typeElement);
        sb.append("    private static final List<FieldMetadata> FIELDS = List.of(\n");
        for (int i = 0; i < fields.size(); i++) {
            FieldInfo field = fields.get(i);
            sb.append("        new Field").append(i).append("Metadata()");
            if (i < fields.size() - 1) {
                sb.append(",");
            }
            sb.append("\n");
        }
        sb.append("    );\n\n");

        // 关联列表（空实现）
        sb.append("    private static final List<RelationMetadata> RELATIONS = Collections.emptyList();\n\n");

        // ==================== EntityMetadata 接口方法 ====================

        sb.append("    @Override\n");
        sb.append("    public Class<").append(typeElement.getSimpleName()).append("> getEntityClass() {\n");
        sb.append("        return entityClass;\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public String getTableName() {\n");
        sb.append("        return TABLE_NAME;\n");
        sb.append("    }\n\n");

        // 主键字段
        FieldInfo idField = fields.stream().filter(f -> f.isId).findFirst().orElse(null);
        if (idField != null) {
            sb.append("    @Override\n");
            sb.append("    public FieldMetadata getIdField() {\n");
            sb.append("        return FIELDS.stream()\n");
            sb.append("            .filter(FieldMetadata::isId)\n");
            sb.append("            .findFirst()\n");
            sb.append("            .orElse(null);\n");
            sb.append("    }\n\n");
        } else {
            sb.append("    @Override\n");
            sb.append("    public FieldMetadata getIdField() {\n");
            sb.append("        return null;\n");
            sb.append("    }\n\n");
        }

        sb.append("    @Override\n");
        sb.append("    public List<FieldMetadata> getFields() {\n");
        sb.append("        return FIELDS;\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public FieldMetadata getField(String propertyName) {\n");
        sb.append("        return FIELDS.stream()\n");
        sb.append("            .filter(f -> f.getPropertyName().equals(propertyName))\n");
        sb.append("            .findFirst()\n");
        sb.append("            .orElse(null);\n");
        sb.append("    }\n\n");

        // 特性标记方法
        sb.append("    @Override\n");
        sb.append("    public boolean isSoftDeletable() {\n");
        sb.append("        return false;\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public boolean isTenantAware() {\n");
        sb.append("        return false;\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public boolean isAuditable() {\n");
        sb.append("        return false;\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public boolean isVersioned() {\n");
        sb.append("        return false;\n");
        sb.append("    }\n\n");

        // 关联方法
        sb.append("    @Override\n");
        sb.append("    public List<RelationMetadata> getRelations() {\n");
        sb.append("        return RELATIONS;\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public Optional<RelationMetadata> getRelation(String fieldName) {\n");
        sb.append("        return Optional.empty();\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public boolean hasRelation(String fieldName) {\n");
        sb.append("        return false;\n");
        sb.append("    }\n\n");

        // ==================== ColumnNameAware 接口方法 ====================

        sb.append("    @Override\n");
        sb.append("    public String getColumnName(String propertyName) {\n");
        sb.append("        FieldMetadata field = getField(propertyName);\n");
        sb.append("        if (field != null) {\n");
        sb.append("            return field.getColumnName();\n");
        sb.append("        }\n");
        sb.append("        // 降级：转换为 snake_case\n");
        sb.append("        return toSnakeCase(propertyName);\n");
        sb.append("    }\n\n");

        sb.append("    private static String toSnakeCase(String name) {\n");
        sb.append("        StringBuilder result = new StringBuilder();\n");
        sb.append("        for (int i = 0; i < name.length(); i++) {\n");
        sb.append("            char c = name.charAt(i);\n");
        sb.append("            if (i > 0 && Character.isUpperCase(c)) {\n");
        sb.append("                result.append('_');\n");
        sb.append("            }\n");
        sb.append("            result.append(Character.toLowerCase(c));\n");
        sb.append("        }\n");
        sb.append("        return result.toString();\n");
        sb.append("    }\n\n");

        // ==================== 字段元数据内部类 ====================

        for (int i = 0; i < fields.size(); i++) {
            sb.append(generateFieldMetadataClass(fields.get(i), i));
        }

        sb.append("}\n");

        return sb.toString();
    }

    /**
     * 生成字段元数据内部类
     */
    private String generateFieldMetadataClass(FieldInfo field, int index) {
        StringBuilder sb = new StringBuilder();
        sb.append("    /**\n");
        sb.append("     * 字段 ").append(field.propertyName).append(" 的元数据\n");
        sb.append("     */\n");
        sb.append("    private static class Field").append(index).append("Metadata implements FieldMetadata {\n");

        sb.append("        @Override\n");
        sb.append("        public String getPropertyName() {\n");
        sb.append("            return \"").append(field.propertyName).append("\";\n");
        sb.append("        }\n\n");

        sb.append("        @Override\n");
        sb.append("        public String getColumnName() {\n");
        sb.append("            return \"").append(field.columnName).append("\";\n");
        sb.append("        }\n\n");

        sb.append("        @Override\n");
        sb.append("        public Class<?> getFieldType() {\n");
        sb.append("            return ").append(field.fieldType).append(".class;\n");
        sb.append("        }\n\n");

        sb.append("        @Override\n");
        sb.append("        public boolean isId() {\n");
        sb.append("            return ").append(field.isId).append(";\n");
        sb.append("        }\n\n");

        sb.append("        @Override\n");
        sb.append("        public boolean isGenerated() {\n");
        sb.append("            return ").append(field.isGenerated).append(";\n");
        sb.append("        }\n");

        sb.append("    }\n\n");
        return sb.toString();
    }

    /**
     * 提取表名
     */
    private String extractTableName(TypeElement typeElement) {
        // 检查 @Table 注解
        for (AnnotationMirror am : typeElement.getAnnotationMirrors()) {
            if (am.getAnnotationType().toString().contains("Table")) {
                for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : am.getElementValues().entrySet()) {
                    if (entry.getKey().getSimpleName().contentEquals("name")) {
                        return entry.getValue().getValue().toString();
                    }
                }
            }
        }
        // 默认：类名转 snake_case
        return toSnakeCase(typeElement.getSimpleName().toString());
    }

    /**
     * 提取字段信息
     */
    private List<FieldInfo> extractFields(TypeElement typeElement) {
        List<FieldInfo> fields = new ArrayList<>();

        for (VariableElement field : ElementFilter.fieldsIn(typeElement.getEnclosedElements())) {
            if (field.getModifiers().contains(Modifier.STATIC)) {
                continue;
            }

            String propertyName = field.getSimpleName().toString();
            String columnName = extractColumnName(field);
            String fieldType = normalizeFieldType(field.asType().toString());
            boolean isId = hasIdAnnotation(field);
            boolean isGenerated = isId;

            fields.add(new FieldInfo(
                propertyName,
                columnName,
                fieldType,
                isId,
                isGenerated
            ));
        }

        return fields;
    }

    /**
     * 提取列名
     */
    private String extractColumnName(VariableElement field) {
        // 检查 @Column 注解
        for (AnnotationMirror am : field.getAnnotationMirrors()) {
            if (am.getAnnotationType().toString().contains("Column")) {
                for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : am.getElementValues().entrySet()) {
                    if (entry.getKey().getSimpleName().contentEquals("name")) {
                        return entry.getValue().getValue().toString();
                    }
                }
            }
        }
        // 默认：camelCase → snake_case
        return toSnakeCase(field.getSimpleName().toString());
    }

    /**
     * 检查是否有 @Id 注解
     */
    private boolean hasIdAnnotation(VariableElement field) {
        for (AnnotationMirror am : field.getAnnotationMirrors()) {
            if (am.getAnnotationType().toString().contains("Id")) {
                return true;
            }
        }
        return "id".equals(field.getSimpleName().toString());
    }

    /**
     * 标准化字段类型
     * <p>
     * 将类型字符串转换为可编译的形式
     */
    private String normalizeFieldType(String type) {
        // 处理基本类型
        switch (type) {
            case "long":
                return "Long";
            case "int":
                return "Integer";
            case "short":
                return "Short";
            case "byte":
                return "Byte";
            case "float":
                return "Float";
            case "double":
                return "Double";
            case "boolean":
                return "Boolean";
            case "char":
                return "Character";
            default:
                return type;
        }
    }

    /**
     * 写入源文件
     */
    private void writeSourceFile(String className, String sourceCode) throws IOException {
        JavaFileObject file = processingEnv.getFiler().createSourceFile(className);
        try (Writer writer = file.openWriter()) {
            writer.write(sourceCode);
        }
    }

    /**
     * 提取包名
     */
    private String extractPackageName(String fullName) {
        int lastDot = fullName.lastIndexOf('.');
        return lastDot > 0 ? fullName.substring(0, lastDot) : "";
    }

    /**
     * camelCase 转 snake_case
     */
    private String toSnakeCase(String name) {
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < name.length(); i++) {
            char c = name.charAt(i);
            if (i > 0 && Character.isUpperCase(c)) {
                result.append('_');
            }
            result.append(Character.toLowerCase(c));
        }
        return result.toString();
    }

    /**
     * 字段信息
     */
    private record FieldInfo(
        String propertyName,
        String columnName,
        String fieldType,
        boolean isId,
        boolean isGenerated
    ) {}
}
