package io.github.afgprojects.framework.apt.entity;

import io.github.afgprojects.framework.commons.naming.NamingUtils;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import java.util.List;
import java.util.Map;

/**
 * 元数据类代码生成器
 * <p>
 * 负责生成实体元数据类的源代码。
 * <p>
 * 生成的元数据类实现 DatabaseEntityMetadata 接口，提供：
 * <ul>
 *   <li>实体类引用</li>
 *   <li>表名</li>
 *   <li>字段元数据列表</li>
 *   <li>关联元数据列表</li>
 *   <li>特性标记方法</li>
 * </ul>
 */
class MetadataCodeGenerator {

    private final ProcessingEnvironment processingEnv;
    private final CommonFieldRegistry commonFieldRegistry;
    private final RelationMetadataGenerator relationMetadataGenerator;

    MetadataCodeGenerator(ProcessingEnvironment processingEnv,
                          CommonFieldRegistry commonFieldRegistry,
                          RelationMetadataGenerator relationMetadataGenerator) {
        this.processingEnv = processingEnv;
        this.commonFieldRegistry = commonFieldRegistry;
        this.relationMetadataGenerator = relationMetadataGenerator;
    }

    /**
     * 验证 SQL 标识符是否安全
     * <p>
     * 只允许字母、数字和下划线，且不能以数字开头。
     * 这可以防止 SQL 注入和语法错误。
     *
     * @param identifier 标识符
     * @return 是否安全
     */
    private boolean isValidSqlIdentifier(String identifier) {
        if (identifier == null || identifier.isEmpty()) {
            return false;
        }
        // 只允许字母、数字、下划线，且不能以数字开头
        return identifier.matches("^[a-zA-Z_][a-zA-Z0-9_]*$");
    }

    /**
     * 验证并转义 SQL 标识符
     * <p>
     * 如果标识符合法，直接返回；否则打印警告并返回空字符串。
     *
     * @param identifier 标识符
     * @param context     上下文描述（用于错误信息）
     * @return 验证后的标识符，非法时返回空字符串
     */
    private String validateSqlIdentifier(String identifier, String context) {
        if (!isValidSqlIdentifier(identifier)) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                "Invalid SQL identifier in " + context + ": '" + identifier +
                "'. Only letters, digits, and underscores are allowed, and it cannot start with a digit.");
            return "";
        }
        return identifier;
    }

    /**
     * 生成元数据类源码
     *
     * @param typeElement        实体类元素
     * @param packageName        包名
     * @param metadataClassName  元数据类名
     * @param tableName          表名
     * @param fields             字段信息列表
     * @param relations          关联信息列表
     * @param features           特性检测结果
     * @return 生成的源码
     */
    String generateMetadataClass(TypeElement typeElement,
                                  String packageName,
                                  String metadataClassName,
                                  String tableName,
                                  List<FieldMetadataGenerator.FieldInfo> fields,
                                  List<RelationMetadataGenerator.RelationInfo> relations,
                                  EntityFeatureDetector.FeatureDetectionResult features) {
        StringBuilder sb = new StringBuilder();

        // 验证表名
        String validatedTableName = validateSqlIdentifier(tableName,
            "table name for entity " + typeElement.getQualifiedName());
        if (validatedTableName.isEmpty()) {
            // 使用默认表名作为降级
            validatedTableName = NamingUtils.toSnakeCase(typeElement.getSimpleName().toString());
        }

        // 包声明
        sb.append("package ").append(packageName).append(".metadata;\n\n");

        // 导入
        sb.append("import io.github.afgprojects.framework.data.core.metadata.*;\n");
        sb.append("import io.github.afgprojects.framework.data.core.relation.*;\n");
        sb.append("import java.util.*;\n");
        sb.append("import java.util.stream.Collectors;\n");
        sb.append("import ").append(typeElement.getQualifiedName()).append(";\n\n");

        // 类注释
        sb.append("/**\n");
        sb.append(" * 自动生成的实体元数据类\n");
        sb.append(" * @generated by AFG Framework APT\n");
        sb.append(" * @see ").append(typeElement.getQualifiedName()).append("\n");
        sb.append(" */\n");

        // 类声明
        sb.append("public class ").append(metadataClassName)
          .append(" implements DatabaseEntityMetadata<").append(typeElement.getSimpleName()).append("> {\n\n");

        // 表名
        sb.append("    private static final String TABLE_NAME = \"").append(validatedTableName).append("\";\n\n");

        // 实体类引用
        sb.append("    private final Class<").append(typeElement.getSimpleName()).append("> entityClass = ")
          .append(typeElement.getSimpleName()).append(".class;\n\n");

        // 字段列表（优先使用通用字段元数据）
        sb.append("    private static final List<FieldMetadata> FIELDS = List.of(\n");
        for (int i = 0; i < fields.size(); i++) {
            FieldMetadataGenerator.FieldInfo field = fields.get(i);
            String fieldMetadataRef = getCommonFieldMetadataRef(field);
            if (fieldMetadataRef != null) {
                // 使用通用字段元数据
                sb.append("        ").append(fieldMetadataRef);
            } else {
                // 生成特定字段的内部类
                sb.append("        new ").append(capitalize(field.propertyName())).append("FieldMetadata()");
            }
            if (i < fields.size() - 1) {
                sb.append(",");
            }
            sb.append("\n");
        }
        sb.append("    );\n\n");

        // 关联列表
        if (!relations.isEmpty()) {
            sb.append("    private static final List<RelationMetadata> RELATIONS = List.of(\n");
            for (int i = 0; i < relations.size(); i++) {
                RelationMetadataGenerator.RelationInfo relation = relations.get(i);
                sb.append("        ").append(relationMetadataGenerator.generateRelationMetadata(relation, typeElement.getSimpleName().toString()));
                if (i < relations.size() - 1) {
                    sb.append(",");
                }
                sb.append("\n");
            }
            sb.append("    );\n\n");
        } else {
            sb.append("    private static final List<RelationMetadata> RELATIONS = Collections.emptyList();\n\n");
        }

        // ==================== EntityMetadata 接口方法 ====================

        sb.append("    @Override\n");
        sb.append("    public Class<").append(typeElement.getSimpleName()).append("> getEntityClass() {\n");
        sb.append("        return entityClass;\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public String getTableName() {\n");
        sb.append("        return TABLE_NAME;\n");
        sb.append("    }\n\n");

        // 主键字段
        sb.append("    @Override\n");
        sb.append("    public DatabaseFieldMetadata getIdField() {\n");
        sb.append("        return (DatabaseFieldMetadata) FIELDS.stream()\n");
        sb.append("            .filter(FieldMetadata::isId)\n");
        sb.append("            .findFirst()\n");
        sb.append("            .orElse(null);\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public List<FieldMetadata> getFields() {\n");
        sb.append("        return FIELDS;\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public DatabaseFieldMetadata getField(String propertyName) {\n");
        sb.append("        return (DatabaseFieldMetadata) FIELDS.stream()\n");
        sb.append("            .filter(f -> f.getPropertyName().equals(propertyName))\n");
        sb.append("            .findFirst()\n");
        sb.append("            .orElse(null);\n");
        sb.append("    }\n\n");

        // 特性标记方法
        sb.append("    @Override\n");
        sb.append("    public boolean isSoftDeletable() {\n");
        sb.append("        return ").append(features.softDeletable()).append(";\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public boolean isTenantAware() {\n");
        sb.append("        return ").append(features.tenantAware()).append(";\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public boolean isAuditable() {\n");
        sb.append("        return ").append(features.auditable()).append(";\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public boolean isVersioned() {\n");
        sb.append("        return ").append(features.versioned()).append(";\n");
        sb.append("    }\n\n");

        // 关联方法
        sb.append("    @Override\n");
        sb.append("    public List<RelationMetadata> getRelations() {\n");
        sb.append("        return RELATIONS;\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public Optional<RelationMetadata> getRelation(String fieldName) {\n");
        sb.append("        return RELATIONS.stream()\n");
        sb.append("            .filter(r -> r.getFieldName().equals(fieldName))\n");
        sb.append("            .findFirst();\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public boolean hasRelation(String fieldName) {\n");
        sb.append("        return RELATIONS.stream()\n");
        sb.append("            .anyMatch(r -> r.getFieldName().equals(fieldName));\n");
        sb.append("    }\n\n");

        // ==================== ColumnNameAware 接口方法 ====================

        sb.append("    @Override\n");
        sb.append("    public String getColumnName(String propertyName) {\n");
        sb.append("        FieldMetadata field = getField(propertyName);\n");
        sb.append("        if (field != null) {\n");
        sb.append("            return field.getColumnName();\n");
        sb.append("        }\n");
        sb.append("        return toSnakeCase(propertyName);\n");
        sb.append("    }\n\n");

        sb.append("    private static String toSnakeCase(String name) {\n");
        sb.append("        StringBuilder result = new StringBuilder();\n");
        sb.append("        for (int i = 0; i < name.length(); i++) {\n");
        sb.append("            char c = name.charAt(i);\n");
        sb.append("            if (i > 0 && Character.isUpperCase(c)) {\n");
        sb.append("                result.append('_');\n");
        sb.append("            }\n");
        sb.append("            result.append(Character.toLowerCase(c));\n");
        sb.append("        }\n");
        sb.append("        return result.toString();\n");
        sb.append("    }\n\n");

        // ==================== 字段元数据内部类（仅生成非通用字段）====================

        for (FieldMetadataGenerator.FieldInfo field : fields) {
            // 跳过通用字段，使用 CommonFieldMetadata
            if (!isCommonField(field)) {
                sb.append(generateFieldMetadataClass(field));
            }
        }

        sb.append("}\n");

        return sb.toString();
    }

    /**
     * 生成字段元数据内部类
     */
    private String generateFieldMetadataClass(FieldMetadataGenerator.FieldInfo field) {
        String className = capitalize(field.propertyName()) + "FieldMetadata";
        StringBuilder sb = new StringBuilder();
        sb.append("    /**\n");
        sb.append("     * 字段 ").append(field.propertyName()).append(" 的元数据\n");
        sb.append("     */\n");
        sb.append("    private static class ").append(className).append(" implements DatabaseFieldMetadata {\n");

        sb.append("        @Override\n");
        sb.append("        public String getPropertyName() {\n");
        sb.append("            return \"").append(escapeJavaString(field.propertyName())).append("\";\n");
        sb.append("        }\n\n");

        // 验证列名
        String columnName = validateSqlIdentifier(field.columnName(),
            "column name for field " + field.propertyName());
        if (columnName.isEmpty()) {
            // 使用默认列名作为降级
            columnName = NamingUtils.toSnakeCase(field.propertyName());
        }

        sb.append("        @Override\n");
        sb.append("        public String getColumnName() {\n");
        sb.append("            return \"").append(columnName).append("\";\n");
        sb.append("        }\n\n");

        sb.append("        @Override\n");
        sb.append("        public Class<?> getFieldType() {\n");
        sb.append("            return ").append(field.fieldType()).append(".class;\n");
        sb.append("        }\n\n");

        sb.append("        @Override\n");
        sb.append("        public boolean isId() {\n");
        sb.append("            return ").append(field.isId()).append(";\n");
        sb.append("        }\n\n");

        sb.append("        @Override\n");
        sb.append("        public boolean isGenerated() {\n");
        sb.append("            return ").append(field.isGenerated()).append(";\n");
        sb.append("        }\n");

        sb.append("    }\n\n");
        return sb.toString();
    }

    /**
     * 转义 Java 字符串中的特殊字符
     *
     * @param str 原始字符串
     * @return 转义后的字符串
     */
    private String escapeJavaString(String str) {
        if (str == null) {
            return "";
        }
        return str.replace("\\", "\\\\")
                  .replace("\"", "\\\"")
                  .replace("\n", "\\n")
                  .replace("\r", "\\r")
                  .replace("\t", "\\t");
    }

    /**
     * 获取通用字段元数据引用
     * <p>
     * 检查字段是否为通用字段，如果是且类型匹配，返回对应的 CommonFieldMetadata 引用代码。
     * 注意：如果字段有自定义列名（@Column(name=...) 与默认 snake_case 不同），则不使用通用字段元数据。
     *
     * @param field 字段信息
     * @return 通用字段元数据引用代码，如 "CommonFieldMetadata.CREATED_AT"；如果不是通用字段则返回 null
     */
    private String getCommonFieldMetadataRef(FieldMetadataGenerator.FieldInfo field) {
        // 如果有自定义列名，不使用通用字段元数据
        if (field.hasCustomColumnName()) {
            return null;
        }

        // 从注册表查找
        CommonFieldInfo commonField = commonFieldRegistry.find(field.propertyName(), field.fieldType());
        if (commonField != null) {
            return commonFieldRegistry.generateRef(commonField);
        }

        return null;
    }

    /**
     * 检查字段是否为通用字段
     *
     * @param field 字段信息
     * @return 是否为通用字段
     */
    private boolean isCommonField(FieldMetadataGenerator.FieldInfo field) {
        return getCommonFieldMetadataRef(field) != null;
    }

    /**
     * 首字母大写
     */
    private String capitalize(String str) {
        if (str == null || str.isEmpty()) {
            return str;
        }
        return Character.toUpperCase(str.charAt(0)) + str.substring(1);
    }

    /**
     * 提取表名
     */
    String extractTableName(TypeElement typeElement) {
        // 检查 @Table 注解
        for (AnnotationMirror am : typeElement.getAnnotationMirrors()) {
            if (am.getAnnotationType().toString().contains("Table")) {
                for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : am.getElementValues().entrySet()) {
                    if (entry.getKey().getSimpleName().contentEquals("name")) {
                        return entry.getValue().getValue().toString();
                    }
                }
            }
        }
        // 默认：类名转 snake_case
        return NamingUtils.toSnakeCase(typeElement.getSimpleName().toString());
    }

    /**
     * 提取 @AfEntity 注解配置
     */
    AfEntityConfig extractAfEntityConfig(TypeElement typeElement) {
        String tableName = null;
        boolean generateRelations = true;

        for (AnnotationMirror am : typeElement.getAnnotationMirrors()) {
            if (am.getAnnotationType().toString().endsWith("AfEntity")) {
                for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : am.getElementValues().entrySet()) {
                    String key = entry.getKey().getSimpleName().toString();
                    Object value = entry.getValue().getValue();

                    if ("tableName".equals(key)) {
                        tableName = value.toString();
                    } else if ("generateRelations".equals(key)) {
                        generateRelations = (Boolean) value;
                    }
                }
                break;
            }
        }

        return new AfEntityConfig(tableName, generateRelations);
    }

    /**
     * AfEntity 注解配置
     */
    record AfEntityConfig(
        String tableName,
        boolean generateRelations
    ) {}
}
