package io.github.afgprojects.framework.apt.entity;

import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.CodeBlock;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.WildcardTypeName;
import io.github.afgprojects.framework.commons.naming.NamingUtils;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import java.util.Collections;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

/**
 * 元数据类代码生成器
 * <p>
 * 负责生成实体元数据类的源代码。使用 JavaPoet 构建 AST，类型安全且可读性强。
 * <p>
 * 生成的元数据类实现 DatabaseEntityMetadata 接口，提供：
 * <ul>
 *   <li>实体类引用</li>
 *   <li>表名</li>
 *   <li>字段元数据列表</li>
 *   <li>关联元数据列表</li>
 *   <li>特性标记方法</li>
 * </ul>
 */
class MetadataCodeGenerator {

    private final ProcessingEnvironment processingEnv;
    private final CommonFieldRegistry commonFieldRegistry;

    // 类型引用
    private static final ClassName NAMING_UTILS = ClassName.get("io.github.afgprojects.framework.commons.naming", "NamingUtils");
    private static final ClassName ENTITY_METADATA = ClassName.get("io.github.afgprojects.framework.data.core.metadata", "DatabaseEntityMetadata");
    private static final ClassName FIELD_METADATA = ClassName.get("io.github.afgprojects.framework.data.core.metadata", "FieldMetadata");
    private static final ClassName DATABASE_FIELD_METADATA = ClassName.get("io.github.afgprojects.framework.data.core.metadata", "DatabaseFieldMetadata");
    private static final ClassName COMMON_FIELD_METADATA = ClassName.get("io.github.afgprojects.framework.data.core.metadata", "CommonFieldMetadata");
    private static final ClassName RELATION_METADATA = ClassName.get("io.github.afgprojects.framework.data.core.relation", "RelationMetadata");
    private static final ClassName RELATION_TYPE = ClassName.get("io.github.afgprojects.framework.data.core.relation", "RelationType");
    private static final ClassName RELATION_METADATA_IMPL = ClassName.get("io.github.afgprojects.framework.data.core.relation", "RelationMetadataImpl");
    private static final ClassName CASCADE_TYPE = ClassName.get("jakarta.persistence", "CascadeType");
    private static final ClassName FETCH_TYPE = ClassName.get("jakarta.persistence", "FetchType");
    private static final ClassName ENTITY_TRAIT = ClassName.get("io.github.afgprojects.framework.data.core.metadata", "EntityTrait");
    private static final ClassName CONDITION = ClassName.get("io.github.afgprojects.framework.data.core.query", "Condition");
    private static final ClassName NO_CONDITION = ClassName.get("io.github.afgprojects.framework.data.core.query", "NoCondition");

    MetadataCodeGenerator(ProcessingEnvironment processingEnv,
                          CommonFieldRegistry commonFieldRegistry) {
        this.processingEnv = processingEnv;
        this.commonFieldRegistry = commonFieldRegistry;
    }

    /**
     * 生成元数据类源码
     *
     * @param typeElement        实体类元素
     * @param packageName        包名
     * @param metadataClassName  元数据类名
     * @param tableName          表名
     * @param fields             字段信息列表
     * @param relations          关联信息列表
     * @param features           特性检测结果
     * @return 生成的源码
     */
    String generateMetadataClass(TypeElement typeElement,
                                  String packageName,
                                  String metadataClassName,
                                  String tableName,
                                  List<FieldMetadataGenerator.FieldInfo> fields,
                                  List<RelationMetadataGenerator.RelationInfo> relations,
                                  EntityFeatureDetector.FeatureDetectionResult features) {
        // 验证表名
        String validatedTableName = validateSqlIdentifier(tableName,
            "table name for entity " + typeElement.getQualifiedName());
        if (validatedTableName.isEmpty()) {
            validatedTableName = NamingUtils.toSnakeCase(typeElement.getSimpleName().toString());
        }

        // 实体类类型
        ClassName entityClass = ClassName.get(typeElement);

        // 构建类
        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(metadataClassName)
            .addModifiers(Modifier.PUBLIC)
            .addSuperinterface(ParameterizedTypeName.get(ENTITY_METADATA, entityClass))
            .addJavadoc("自动生成的实体元数据类\n")
            .addJavadoc("@generated by AFG Framework APT\n")
            .addJavadoc("@see $L\n", typeElement.getQualifiedName().toString());

        // 表名常量
        classBuilder.addField(FieldSpec.builder(String.class, "TABLE_NAME",
                Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
            .initializer("$S", validatedTableName)
            .build());

        // 实体类引用
        classBuilder.addField(FieldSpec.builder(
                ParameterizedTypeName.get(ClassName.get(Class.class), entityClass),
                "entityClass",
                Modifier.PRIVATE, Modifier.FINAL)
            .initializer("$T.class", entityClass)
            .build());

        // 字段列表
        classBuilder.addField(FieldSpec.builder(
                ParameterizedTypeName.get(ClassName.get(List.class), FIELD_METADATA),
                "FIELDS",
                Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
            .initializer(buildFieldsInitializer(fields))
            .build());

        // 关联列表
        classBuilder.addField(FieldSpec.builder(
                ParameterizedTypeName.get(ClassName.get(List.class), RELATION_METADATA),
                "RELATIONS",
                Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
            .initializer(buildRelationsInitializer(relations, entityClass))
            .build());

        // 添加接口方法
        addInterfaceMethods(classBuilder, entityClass, features);

        // 添加 getColumnName 方法
        addGetColumnNameMethod(classBuilder);

        // 添加字段元数据内部类（仅非通用字段）
        for (FieldMetadataGenerator.FieldInfo field : fields) {
            if (!isCommonField(field)) {
                classBuilder.addType(buildFieldMetadataInnerClass(field));
            }
        }

        // 生成 Java 文件（JavaPoet 会自动添加必要的导入）
        JavaFile javaFile = JavaFile.builder(packageName + ".metadata", classBuilder.build())
            .addFileComment("Auto-generated by AFG Framework APT")
            .build();

        return javaFile.toString();
    }

    /**
     * 构建字段列表初始化代码
     */
    private CodeBlock buildFieldsInitializer(List<FieldMetadataGenerator.FieldInfo> fields) {
        CodeBlock.Builder builder = CodeBlock.builder();
        builder.add("$T.of(\n", ClassName.get(List.class));

        for (int i = 0; i < fields.size(); i++) {
            FieldMetadataGenerator.FieldInfo field = fields.get(i);
            String fieldMetadataRef = getCommonFieldMetadataRef(field);

            if (fieldMetadataRef != null) {
                // 使用完整类名引用
                builder.add("    $T.$L", COMMON_FIELD_METADATA, fieldMetadataRef);
            } else {
                builder.add("    new $LFieldMetadata()", capitalize(field.propertyName()));
            }

            if (i < fields.size() - 1) {
                builder.add(",");
            }
            builder.add("\n");
        }

        builder.add(")");
        return builder.build();
    }

    /**
     * 构建关联列表初始化代码
     */
    private CodeBlock buildRelationsInitializer(List<RelationMetadataGenerator.RelationInfo> relations, ClassName entityClass) {
        if (relations.isEmpty()) {
            return CodeBlock.builder().add("$T.emptyList()", ClassName.get(Collections.class)).build();
        }

        CodeBlock.Builder builder = CodeBlock.builder();
        builder.add("$T.of(\n", ClassName.get(List.class));

        for (int i = 0; i < relations.size(); i++) {
            RelationMetadataGenerator.RelationInfo relation = relations.get(i);
            builder.add("    $L", buildRelationMetadata(relation, entityClass.simpleName()));

            if (i < relations.size() - 1) {
                builder.add(",");
            }
            builder.add("\n");
        }

        builder.add(")");
        return builder.build();
    }

    /**
     * 构建单个关联元数据
     */
    private CodeBlock buildRelationMetadata(RelationMetadataGenerator.RelationInfo relation, String entitySimpleName) {
        CodeBlock.Builder builder = CodeBlock.builder();
        builder.add("$T.builder()\n", RELATION_METADATA_IMPL);
        builder.add("    .relationType($T.$L)\n", RELATION_TYPE, relation.relationType());
        builder.add("    .entityClass($L.class)\n", entitySimpleName);
        builder.add("    .targetEntityClass($L.class)\n", relation.targetEntity());
        builder.add("    .fieldName($S)\n", relation.fieldName());

        if (relation.mappedBy() != null && !relation.mappedBy().isEmpty()) {
            builder.add("    .mappedBy($S)\n", relation.mappedBy());
        }

        builder.add("    .foreignKeyColumn($S)\n", relation.foreignKeyColumn());

        if (relation.joinTable() != null && !relation.joinTable().isEmpty()) {
            builder.add("    .joinTable($S)\n", relation.joinTable());
        }
        if (relation.joinColumn() != null && !relation.joinColumn().isEmpty()) {
            builder.add("    .joinColumn($S)\n", relation.joinColumn());
        }
        if (relation.inverseJoinColumn() != null && !relation.inverseJoinColumn().isEmpty()) {
            builder.add("    .inverseJoinColumn($S)\n", relation.inverseJoinColumn());
        }

        // 级联类型
        builder.add("    .cascadeTypes(");
        if (relation.cascadeTypes().isEmpty()) {
            builder.add("$T.emptySet()", ClassName.get(Collections.class));
        } else {
            builder.add("$T.of(", ClassName.get(EnumSet.class));
            for (int i = 0; i < relation.cascadeTypes().size(); i++) {
                if (i > 0) builder.add(", ");
                builder.add("$T.$L", CASCADE_TYPE, relation.cascadeTypes().get(i));
            }
            builder.add(")");
        }
        builder.add(")\n");

        builder.add("    .fetchType($T.$L)\n", FETCH_TYPE, relation.fetchType());
        builder.add("    .orphanRemoval($L)\n", relation.orphanRemoval());
        builder.add("    .optional($L)\n", relation.optional());
        builder.add("    .build()");

        return builder.build();
    }

    /**
     * 添加接口方法
     */
    private void addInterfaceMethods(TypeSpec.Builder classBuilder, ClassName entityClass,
                                      EntityFeatureDetector.FeatureDetectionResult features) {
        // getEntityClass
        classBuilder.addMethod(MethodSpec.methodBuilder("getEntityClass")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(ParameterizedTypeName.get(ClassName.get(Class.class), entityClass))
            .addStatement("return entityClass")
            .build());

        // getTableName
        classBuilder.addMethod(MethodSpec.methodBuilder("getTableName")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(String.class)
            .addStatement("return TABLE_NAME")
            .build());

        // getIdField
        classBuilder.addMethod(MethodSpec.methodBuilder("getIdField")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(DATABASE_FIELD_METADATA)
            .addStatement("return ($T) FIELDS.stream()\n" +
                "    .filter($T::isId)\n" +
                "    .findFirst()\n" +
                "    .orElse(null)", DATABASE_FIELD_METADATA, FIELD_METADATA)
            .build());

        // getFields
        classBuilder.addMethod(MethodSpec.methodBuilder("getFields")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(ParameterizedTypeName.get(ClassName.get(List.class), FIELD_METADATA))
            .addStatement("return FIELDS")
            .build());

        // getField
        classBuilder.addMethod(MethodSpec.methodBuilder("getField")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .addParameter(String.class, "propertyName")
            .returns(DATABASE_FIELD_METADATA)
            .addStatement("return ($T) FIELDS.stream()\n" +
                "    .filter(f -> f.getPropertyName().equals(propertyName))\n" +
                "    .findFirst()\n" +
                "    .orElse(null)", DATABASE_FIELD_METADATA)
            .build());

        // 关联方法
        classBuilder.addMethod(MethodSpec.methodBuilder("getRelations")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(ParameterizedTypeName.get(ClassName.get(List.class), RELATION_METADATA))
            .addStatement("return RELATIONS")
            .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("getRelation")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .addParameter(String.class, "fieldName")
            .returns(ParameterizedTypeName.get(ClassName.get(Optional.class), RELATION_METADATA))
            .addStatement("return RELATIONS.stream()\n" +
                "    .filter(r -> r.getFieldName().equals(fieldName))\n" +
                "    .findFirst()")
            .build());

        classBuilder.addMethod(MethodSpec.methodBuilder("hasRelation")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .addParameter(String.class, "fieldName")
            .returns(boolean.class)
            .addStatement("return RELATIONS.stream()\n" +
                "    .anyMatch(r -> r.getFieldName().equals(fieldName))")
            .build());

        // getIdFieldName
        classBuilder.addMethod(MethodSpec.methodBuilder("getIdFieldName")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(String.class)
            .addStatement("$T idField = getIdField()", FIELD_METADATA)
            .addStatement("return idField != null ? idField.getPropertyName() : \"id\"")
            .build());

        // getSoftDeleteField
        classBuilder.addMethod(MethodSpec.methodBuilder("getSoftDeleteField")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(FIELD_METADATA)
            .addStatement("$T deleted = getField(\"deleted\")", FIELD_METADATA)
            .addStatement("return deleted != null ? deleted : getField(\"deletedAt\")")
            .build());

        // getTenantField
        classBuilder.addMethod(MethodSpec.methodBuilder("getTenantField")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(FIELD_METADATA)
            .addStatement("return getField(\"tenantId\")")
            .build());

        // getColumnToFieldMap
        classBuilder.addMethod(MethodSpec.methodBuilder("getColumnToFieldMap")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(ParameterizedTypeName.get(ClassName.get(Map.class), ClassName.get(String.class), ClassName.get(String.class)))
            .addStatement("$T<String, String> map = new $T<>()", ClassName.get(Map.class), ClassName.get(HashMap.class))
            .beginControlFlow("for ($T field : FIELDS)", FIELD_METADATA)
            .addStatement("map.put(field.getColumnName(), field.getPropertyName())")
            .endControlFlow()
            .addStatement("return map")
            .build());

        // getFieldToColumnMap
        classBuilder.addMethod(MethodSpec.methodBuilder("getFieldToColumnMap")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(ParameterizedTypeName.get(ClassName.get(Map.class), ClassName.get(String.class), ClassName.get(String.class)))
            .addStatement("$T<String, String> map = new $T<>()", ClassName.get(Map.class), ClassName.get(HashMap.class))
            .beginControlFlow("for ($T field : FIELDS)", FIELD_METADATA)
            .addStatement("map.put(field.getPropertyName(), field.getColumnName())")
            .endControlFlow()
            .addStatement("return map")
            .build());

        // hasTrait
        classBuilder.addMethod(MethodSpec.methodBuilder("hasTrait")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .addParameter(ENTITY_TRAIT, "trait")
            .returns(boolean.class)
            .addStatement("return getTraits().contains(trait)")
            .build());

        // getTraits
        MethodSpec.Builder getTraitsBuilder = MethodSpec.methodBuilder("getTraits")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(ParameterizedTypeName.get(ClassName.get(Set.class), ENTITY_TRAIT))
            .addStatement("$T<$T> traits = $T.noneOf($T.class)", ClassName.get(EnumSet.class), ENTITY_TRAIT, ClassName.get(EnumSet.class), ENTITY_TRAIT);

        // 基于特性检测结果直接添加 trait（不再调用废弃的 isSoftDeletable/isTenantAware/isAuditable/isVersioned 方法）
        if (features.softDeletable()) {
            getTraitsBuilder.addStatement("traits.add($T.SOFT_DELETABLE)", ENTITY_TRAIT);
        }
        if (features.timestampSoftDeletable()) {
            getTraitsBuilder.addStatement("traits.add($T.TIMESTAMP_SOFT_DELETABLE)", ENTITY_TRAIT);
        }
        if (features.tenantAware()) {
            getTraitsBuilder.addStatement("traits.add($T.TENANT_AWARE)", ENTITY_TRAIT);
        }
        if (features.timestamped()) {
            getTraitsBuilder.addStatement("traits.add($T.TIMESTAMPED)", ENTITY_TRAIT);
        }
        if (features.auditable()) {
            getTraitsBuilder.addStatement("traits.add($T.AUDITABLE)", ENTITY_TRAIT);
        }
        if (features.versioned()) {
            getTraitsBuilder.addStatement("traits.add($T.VERSIONED)", ENTITY_TRAIT);
        }
        if (features.dataScopeAware()) {
            getTraitsBuilder.addStatement("traits.add($T.DATA_SCOPE_AWARE)", ENTITY_TRAIT);
        }
        getTraitsBuilder.addStatement("return traits");
        classBuilder.addMethod(getTraitsBuilder.build());

        // getDefaultCondition
        classBuilder.addMethod(MethodSpec.methodBuilder("getDefaultCondition")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(CONDITION)
            .addStatement("return $T.empty()", CONDITION)
            .build());
    }

    /**
     * 添加 getColumnName 方法（使用 NamingUtils.toSnakeCase）
     */
    private void addGetColumnNameMethod(TypeSpec.Builder classBuilder) {
        classBuilder.addMethod(MethodSpec.methodBuilder("getColumnName")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .addParameter(String.class, "propertyName")
            .returns(String.class)
            .addStatement("$T field = getField(propertyName)", FIELD_METADATA)
            .beginControlFlow("if (field != null)")
            .addStatement("return field.getColumnName()")
            .endControlFlow()
            .addStatement("return $T.toSnakeCase(propertyName)", NAMING_UTILS)
            .build());
    }

    /**
     * 构建字段元数据内部类
     */
    private TypeSpec buildFieldMetadataInnerClass(FieldMetadataGenerator.FieldInfo field) {
        String className = capitalize(field.propertyName()) + "FieldMetadata";

        // 验证列名
        String columnName = validateSqlIdentifier(field.columnName(),
            "column name for field " + field.propertyName());
        if (columnName.isEmpty()) {
            columnName = NamingUtils.toSnakeCase(field.propertyName());
        }

        return TypeSpec.classBuilder(className)
            .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
            .addSuperinterface(DATABASE_FIELD_METADATA)
            .addJavadoc("字段 $L 的元数据\n", field.propertyName())
            .addMethod(MethodSpec.methodBuilder("getPropertyName")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(String.class)
                .addStatement("return $S", field.propertyName())
                .build())
            .addMethod(MethodSpec.methodBuilder("getColumnName")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(String.class)
                .addStatement("return $S", columnName)
                .build())
            .addMethod(MethodSpec.methodBuilder("getFieldType")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(ParameterizedTypeName.get(ClassName.get(Class.class), WildcardTypeName.subtypeOf(Object.class)))
                .addStatement("return $L.class", field.fieldType())
                .build())
            .addMethod(MethodSpec.methodBuilder("isId")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(boolean.class)
                .addStatement("return $L", field.isId())
                .build())
            .addMethod(MethodSpec.methodBuilder("isGenerated")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(boolean.class)
                .addStatement("return $L", field.isGenerated())
                .build())
            .build();
    }

    /**
     * 验证 SQL 标识符是否安全
     */
    private boolean isValidSqlIdentifier(String identifier) {
        if (identifier == null || identifier.isEmpty()) {
            return false;
        }
        return identifier.matches("^[a-zA-Z_][a-zA-Z0-9_]*$");
    }

    /**
     * 验证并转义 SQL 标识符
     */
    private String validateSqlIdentifier(String identifier, String context) {
        if (!isValidSqlIdentifier(identifier)) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                "Invalid SQL identifier in " + context + ": '" + identifier +
                "'. Only letters, digits, and underscores are allowed, and it cannot start with a digit.");
            return "";
        }
        return identifier;
    }

    /**
     * 获取通用字段元数据引用
     */
    private String getCommonFieldMetadataRef(FieldMetadataGenerator.FieldInfo field) {
        if (field.hasCustomColumnName()) {
            return null;
        }

        CommonFieldInfo commonField = commonFieldRegistry.find(field.propertyName(), field.fieldType());
        if (commonField != null) {
            return commonFieldRegistry.generateRef(commonField);
        }

        return null;
    }

    /**
     * 检查字段是否为通用字段
     */
    private boolean isCommonField(FieldMetadataGenerator.FieldInfo field) {
        return getCommonFieldMetadataRef(field) != null;
    }

    /**
     * 首字母大写
     */
    private String capitalize(String str) {
        if (str == null || str.isEmpty()) {
            return str;
        }
        return Character.toUpperCase(str.charAt(0)) + str.substring(1);
    }

    /**
     * 提取表名
     */
    String extractTableName(TypeElement typeElement) {
        for (AnnotationMirror am : typeElement.getAnnotationMirrors()) {
            if (am.getAnnotationType().toString().contains("Table")) {
                for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : am.getElementValues().entrySet()) {
                    if (entry.getKey().getSimpleName().contentEquals("name")) {
                        return entry.getValue().getValue().toString();
                    }
                }
            }
        }
        return NamingUtils.toSnakeCase(typeElement.getSimpleName().toString());
    }

    /**
     * 提取 @AfEntity 注解配置
     */
    AfEntityConfig extractAfEntityConfig(TypeElement typeElement) {
        String tableName = null;
        boolean generateRelations = true;
        boolean autoFillTimestamps = true;

        for (AnnotationMirror am : typeElement.getAnnotationMirrors()) {
            if (am.getAnnotationType().toString().endsWith("AfEntity")) {
                for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : am.getElementValues().entrySet()) {
                    String key = entry.getKey().getSimpleName().toString();
                    Object value = entry.getValue().getValue();

                    if ("tableName".equals(key)) {
                        tableName = value.toString();
                    } else if ("generateRelations".equals(key)) {
                        generateRelations = (Boolean) value;
                    } else if ("autoFillTimestamps".equals(key)) {
                        autoFillTimestamps = (Boolean) value;
                    }
                }
                break;
            }
        }

        return new AfEntityConfig(tableName, generateRelations, autoFillTimestamps);
    }

    /**
     * AfEntity 注解配置
     */
    record AfEntityConfig(
        String tableName,
        boolean generateRelations,
        boolean autoFillTimestamps
    ) {}
}
