package io.github.afgprojects.framework.apt.service;

import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.CodeBlock;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import java.util.Collections;
import java.util.List;

/**
 * Service metadata code generator.
 * <p>
 * Uses JavaPoet to generate a class that implements {@code ServiceMetadata<T>}
 * from the core invocation module. The generated class provides compile-time
 * metadata for @AfService-annotated classes.
 */
class ServiceMetadataCodeGenerator {

    private final ProcessingEnvironment processingEnv;

    // Type references
    private static final ClassName SERVICE_METADATA =
        ClassName.get("io.github.afgprojects.framework.core.invocation", "ServiceMetadata");
    private static final ClassName OPERATION_METADATA =
        ClassName.get("io.github.afgprojects.framework.core.invocation", "OperationMetadata");
    private static final ClassName PARAMETER_METADATA =
        ClassName.get("io.github.afgprojects.framework.core.invocation", "ParameterMetadata");
    private static final ClassName SIMPLE_OPERATION_METADATA =
        ClassName.get("io.github.afgprojects.framework.core.invocation", "SimpleOperationMetadata");
    private static final ClassName SIMPLE_PARAMETER_METADATA =
        ClassName.get("io.github.afgprojects.framework.core.invocation", "SimpleParameterMetadata");
    private static final ClassName METHOD_KEY =
        ClassName.get("io.github.afgprojects.framework.core.invocation", "MethodKey");

    ServiceMetadataCodeGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
    }

    /**
     * Generate the ServiceMetadata implementation class source code.
     *
     * @param typeElement       the @AfService-annotated class
     * @param packageName       the package name for the generated class
     * @param metadataClassName the simple name of the generated class
     * @param serviceConfig     extracted @AfService configuration
     * @param operations        extracted operation info list
     * @return the generated Java source code
     */
    String generateMetadataClass(TypeElement typeElement,
                                  String packageName,
                                  String metadataClassName,
                                  ServiceMetadataProcessor.AfServiceConfig serviceConfig,
                                  List<ServiceMetadataProcessor.OperationInfo> operations) {
        ClassName serviceClass = ClassName.get(typeElement);

        // Build the class
        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(metadataClassName)
            .addModifiers(Modifier.PUBLIC)
            .addSuperinterface(ParameterizedTypeName.get(SERVICE_METADATA, serviceClass))
            .addJavadoc("Auto-generated service metadata class\n")
            .addJavadoc("@generated by AFG Framework APT\n")
            .addJavadoc("@see $L\n", typeElement.getQualifiedName().toString());

        // @Generated annotation
        classBuilder.addAnnotation(AnnotationSpec.builder(ClassName.get("javax.annotation.processing", "Generated"))
            .addMember("value", "$S", "AFG Service Metadata Processor")
            .build());

        // Service name constant
        classBuilder.addField(FieldSpec.builder(String.class, "SERVICE_NAME",
                Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
            .initializer("$S", serviceConfig.name())
            .build());

        // Service type field
        classBuilder.addField(FieldSpec.builder(
                ParameterizedTypeName.get(ClassName.get(Class.class), serviceClass),
                "serviceType",
                Modifier.PRIVATE, Modifier.FINAL)
            .initializer("$T.class", serviceClass)
            .build());

        // OPERATIONS field
        classBuilder.addField(FieldSpec.builder(
                ParameterizedTypeName.get(ClassName.get(List.class), OPERATION_METADATA),
                "OPERATIONS",
                Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
            .initializer(buildOperationsInitializer(operations, serviceClass))
            .build());

        // Add interface methods
        addInterfaceMethods(classBuilder, serviceClass, serviceConfig);

        // Generate Java file
        JavaFile javaFile = JavaFile.builder(packageName + ".metadata", classBuilder.build())
            .addFileComment("Auto-generated by AFG Framework APT")
            .build();

        return javaFile.toString();
    }

    /**
     * Build the OPERATIONS field initializer code block.
     */
    private CodeBlock buildOperationsInitializer(List<ServiceMetadataProcessor.OperationInfo> operations,
                                                  ClassName serviceClass) {
        if (operations.isEmpty()) {
            return CodeBlock.builder().add("$T.emptyList()", ClassName.get(Collections.class)).build();
        }

        CodeBlock.Builder builder = CodeBlock.builder();
        builder.add("$T.of(\n", ClassName.get(List.class));

        for (int i = 0; i < operations.size(); i++) {
            ServiceMetadataProcessor.OperationInfo op = operations.get(i);
            builder.add("    $L", buildOperationMetadata(op, serviceClass));

            if (i < operations.size() - 1) {
                builder.add(",");
            }
            builder.add("\n");
        }

        builder.add(")");
        return builder.build();
    }

    /**
     * Build a single SimpleOperationMetadata instantiation.
     */
    private CodeBlock buildOperationMetadata(ServiceMetadataProcessor.OperationInfo op,
                                              ClassName serviceClass) {
        ServiceMetadataProcessor.AfOperationConfig config = op.operationConfig();
        ServiceMetadataProcessor.AfResultConfig resultConfig = op.resultConfig();
        ExecutableElement method = op.method();

        CodeBlock.Builder builder = CodeBlock.builder();
        builder.add("new $T(\n", SIMPLE_OPERATION_METADATA);

        // name
        builder.add("    $S,\n", config.name());

        // description
        builder.add("    $S,\n", config.description());

        // method (MethodKey)
        builder.add("    new $T($S, $T.of($L)),\n",
            METHOD_KEY,
            method.getSimpleName().toString(),
            ClassName.get(List.class),
            buildParameterTypesList(method));

        // parameters
        builder.add("    $L,\n", buildParametersInitializer(op.parameters()));

        // returnType
        builder.add("    $S,\n", method.getReturnType().toString());

        // returnDescription (from @AfResult)
        builder.add("    $S,\n", resultConfig.description());

        // permission
        builder.add("    $S,\n", config.permission());

        // requiredRoles
        builder.add("    $L,\n", buildStringList(config.requiredRoles()));

        // audit
        builder.add("    $L,\n", config.audit());

        // tenantScope
        builder.add("    $L,\n", config.tenantScope());

        // dataScope
        builder.add("    $L,\n", config.dataScope());

        // async
        builder.add("    $L,\n", config.async());

        // deprecated
        builder.add("    $L,\n", config.deprecated());

        // inputSchema
        builder.add("    $S,\n", config.inputSchema());

        // paged (from @AfResult)
        builder.add("    $L\n", resultConfig.paged());

        builder.add(")");
        return builder.build();
    }

    /**
     * Build the parameter types list for MethodKey constructor.
     */
    private String buildParameterTypesList(ExecutableElement method) {
        List<? extends javax.lang.model.element.VariableElement> params = method.getParameters();
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < params.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append("\"").append(params.get(i).asType().toString()).append("\"");
        }
        return sb.toString();
    }

    /**
     * Build the parameters list initializer for an operation.
     */
    private CodeBlock buildParametersInitializer(List<ServiceMetadataProcessor.ParameterInfo> parameters) {
        if (parameters.isEmpty()) {
            return CodeBlock.builder().add("$T.emptyList()", ClassName.get(Collections.class)).build();
        }

        CodeBlock.Builder builder = CodeBlock.builder();
        builder.add("$T.of(\n", ClassName.get(List.class));

        for (int i = 0; i < parameters.size(); i++) {
            ServiceMetadataProcessor.ParameterInfo param = parameters.get(i);
            builder.add("    new $T(\n", SIMPLE_PARAMETER_METADATA);
            builder.add("        $S,\n", param.name());
            builder.add("        $S,\n", param.type());
            builder.add("        $L,\n", param.required());
            builder.add("        $S,\n", param.defaultValue());
            builder.add("        $L,\n", param.index());
            builder.add("        $S,\n", param.description());
            builder.add("        $L,\n", buildStringList(param.enumValues()));
            builder.add("        $L\n", param.injected());
            builder.add("    )");

            if (i < parameters.size() - 1) {
                builder.add(",");
            }
            builder.add("\n");
        }

        builder.add(")");
        return builder.build();
    }

    /**
     * Build a List.of(...) code block for a list of strings.
     */
    private CodeBlock buildStringList(List<String> values) {
        if (values == null || values.isEmpty()) {
            return CodeBlock.builder().add("$T.emptyList()", ClassName.get(Collections.class)).build();
        }

        CodeBlock.Builder builder = CodeBlock.builder();
        builder.add("$T.of(", ClassName.get(List.class));
        for (int i = 0; i < values.size(); i++) {
            if (i > 0) builder.add(", ");
            builder.add("$S", values.get(i));
        }
        builder.add(")");
        return builder.build();
    }

    /**
     * Add all ServiceMetadata interface methods.
     */
    private void addInterfaceMethods(TypeSpec.Builder classBuilder,
                                      ClassName serviceClass,
                                      ServiceMetadataProcessor.AfServiceConfig serviceConfig) {
        // serviceName()
        classBuilder.addMethod(MethodSpec.methodBuilder("serviceName")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(String.class)
            .addStatement("return SERVICE_NAME")
            .build());

        // description()
        classBuilder.addMethod(MethodSpec.methodBuilder("description")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(String.class)
            .addStatement("return $S", serviceConfig.description())
            .build());

        // category()
        classBuilder.addMethod(MethodSpec.methodBuilder("category")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(String.class)
            .addStatement("return $S", serviceConfig.category())
            .build());

        // tags()
        classBuilder.addMethod(MethodSpec.methodBuilder("tags")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(ParameterizedTypeName.get(ClassName.get(List.class), ClassName.get(String.class)))
            .addStatement("return $L", buildStringList(serviceConfig.tags()))
            .build());

        // icon()
        classBuilder.addMethod(MethodSpec.methodBuilder("icon")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(String.class)
            .addStatement("return $S", serviceConfig.icon())
            .build());

        // examples()
        classBuilder.addMethod(MethodSpec.methodBuilder("examples")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(ParameterizedTypeName.get(ClassName.get(List.class), ClassName.get(String.class)))
            .addStatement("return $L", buildStringList(serviceConfig.examples()))
            .build());

        // serviceType()
        classBuilder.addMethod(MethodSpec.methodBuilder("serviceType")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(ParameterizedTypeName.get(ClassName.get(Class.class), serviceClass))
            .addStatement("return serviceType")
            .build());

        // operations()
        classBuilder.addMethod(MethodSpec.methodBuilder("operations")
            .addAnnotation(Override.class)
            .addModifiers(Modifier.PUBLIC)
            .returns(ParameterizedTypeName.get(ClassName.get(List.class), OPERATION_METADATA))
            .addStatement("return OPERATIONS")
            .build());
    }
}
